Repository team-archivist/archivist-backend, pull requests merged in 2023-12, with the labels that each got.

#13 refactor: 카카오 소셜 로그인 구현 (#5)
  build.gradle
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/WebClientConfig.java
  src/main/java/com/beside/archivist/controller/KakaoLoginController.java
  src/main/java/com/beside/archivist/dto/KakaoLoginDto.java
  src/main/java/com/beside/archivist/service/KakaoService.java
  src/main/java/com/beside/archivist/service/KakaoServiceImpl.java
  src/main/resources/application.properties
Labels: refactor

#24 feat: 북마크 CRUD (#12)
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/dto/bookmark/BookmarkDto.java
  src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java
  src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
Labels: feature

#29 feat: 회원 정보 조회 기능 추가 (#11)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature

#30 feat : BaseEntity 생성 (#20)
  src/main/java/com/beside/archivist/ArchivistApplication.java
  src/main/java/com/beside/archivist/entity/BaseEntity.java
  src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java
  src/main/java/com/beside/archivist/entity/users/User.java
Labels: feature

#34 feat: 회원 이미지 업로드 기능 추가 (#21)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/WebMvcConfig.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/users/UserInfoDto.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/entity/users/UserImg.java
  src/main/java/com/beside/archivist/repository/users/UserImgRepository.java
  src/main/java/com/beside/archivist/service/users/UserImgService.java
  src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
  src/main/java/com/beside/archivist/service/util/FileService.java
  src/main/resources/application.properties
  src/main/resources/static/images/userDefaultImg.png
Labels: feature

#36 chore: 회원 이미지 경로 설정 (#35)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/WebMvcConfig.java
  src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/static/default-image/userDefaultImg.png
Labels: chore, fix

#38 feat: 등록/수정자 추적을 위한 AuditorAware 설정 추가 (#37)
  src/main/java/com/beside/archivist/ArchivistApplication.java
  src/main/java/com/beside/archivist/config/AuditConfig.java
  src/main/java/com/beside/archivist/config/AuditorAwareImpl.java
Labels: feature

#43 refactor: 회원 조회 API 변경 (#42)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: refactor

#45 feat: 공통 예외 처리 베이스 구축 (#22)
  src/main/java/com/beside/archivist/exception/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/ExceptionResponse.java
  src/main/java/com/beside/archivist/exception/GlobalExceptionController.java
Labels: feature

#49 feat: 중복 회원 검증 로직 추가 (#44)
  src/main/java/com/beside/archivist/exception/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/users/UserAlreadyExistsException.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature

#51 feat: 회원 연관관계 매핑 추가 (#50)
  src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
Labels: feature, fix

#54 fix: 북마크 등록시 유저 값 처리 (#53)
  settings.gradle
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkImgService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
Labels: fix

#55 refactor : 이미지 경로 수정 (#48)
  src/main/java/com/beside/archivist/service/bookmark/BookmarkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: refactor

#58 refactor : 북마크 디폴트 이미지 생성 & 북마크 리팩토링 (#56)
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/dto/bookmark/BookmarkDto.java
  src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkImgService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
Labels: feature, refactor

#59 refactor: 소셜 로그인 시 코드 리팩토링 및 예외 처리 개선 (#52)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/users/KakaoLoginDto.java
  src/main/java/com/beside/archivist/exception/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/users/UserNotFoundException.java
  src/main/java/com/beside/archivist/service/users/KakaoService.java
  src/main/java/com/beside/archivist/service/users/KakaoServiceImpl.java
Labels: refactor

#61 refactor : 서비스 용어 변경으로 북마크 리팩토링 (#60)
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/dto/link/LinkDto.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/entity/link/LinkImg.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/repository/bookmark/BookmarkImgRepository.java
  src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java
  src/main/java/com/beside/archivist/repository/link/LinkImgRepository.java
  src/main/java/com/beside/archivist/repository/link/LinkRepository.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkImgService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkImgService.java
  src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: refactor

#62 feat: 회원 유효성 검증 및 예외 처리 (#44)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/users/UserDto.java
  src/main/java/com/beside/archivist/exception/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/ValidExceptionDto.java
Labels: feature

#64 refactor: 객체명 변경 및 패키지 이동 (#63)
  src/main/java/com/beside/archivist/dto/exception/ExceptionDto.java
  src/main/java/com/beside/archivist/dto/exception/ValidExceptionDto.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/users/UserAlreadyExistsException.java
  src/main/java/com/beside/archivist/exception/users/UserNotFoundException.java
  src/main/java/com/beside/archivist/service/users/KakaoServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: refactor

#66 fix: 회원 수정 API 개선 (#65)
  src/main/java/com/beside/archivist/controller/users/UserController.java
Labels: fix, refactor

#68 feature : 북마크 유효성 검증 - title, description (#57)
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/dto/link/LinkDto.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: feature

#69 Category 값 재정의 및 조회 API 구현 (#67)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/entity/users/Category.java
Labels: feature, refactor
