Repository team-archivist/archivist-backend, pull requests merged in 2024-01, with the labels that each got.

#74 feat: 이미지 업로드 시 jpg/jpeg/png 외 확장자 예외 처리 추가 (#70)
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/images/InvalidFileExtensionException.java
  src/main/java/com/beside/archivist/service/util/FileService.java
Labels: feature

#75 feat: 그룹 crud 추가 및 연관관계 매핑 (#73)
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
  src/main/java/com/beside/archivist/dto/group/GroupDto.java
  src/main/java/com/beside/archivist/dto/group/LinkGroupDto.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/group/GroupImg.java
  src/main/java/com/beside/archivist/entity/group/LinkGroup.java
  src/main/java/com/beside/archivist/repository/group/GroupImgRepository.java
  src/main/java/com/beside/archivist/repository/group/GroupRepository.java
  src/main/java/com/beside/archivist/repository/group/LinkGroupRepository.java
  src/main/java/com/beside/archivist/service/group/GroupImgService.java
  src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/group/LinkGroupService.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: feature

#76 refactor: Mapstruct 적용하여 중복 코드 제거 (#47)
  build.gradle
  src/main/java/com/beside/archivist/mapper/GroupMapper.java
  src/main/java/com/beside/archivist/mapper/LinkGroupMapper.java
  src/main/java/com/beside/archivist/mapper/LinkMapper.java
  src/main/java/com/beside/archivist/mapper/UserMapper.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: refactor

#77 feat: 이미지 업로드 시 10MB 이상 파일에 대한 예외 처리 추가 (#70)
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: feature

#79 feat: 회원과 그룹간 Bookmark 테이블 작업 (#71)
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/dto/group/GroupDto.java
  src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/mapper/GroupMapper.java
  src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java
  src/main/java/com/beside/archivist/repository/group/GroupRepository.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature, refactor

#83 chore: 카테고리 조회 API 인증 해제 (#67)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
Labels: chore

#85 feature : NCP 스토리지로 이미지 저장소 변경 (#72)
  src/main/resources/application-prod.properties
Labels: feature

#84 feat: 로그인 API 응답 시 헤더에 Token 추가 (#82)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
Labels: feature

#94 feat: 닉네임 조회 API 구현 (#86)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature

#95 feat: 정의되지 않은 카테고리 값 예외 처리 (#87)
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/users/InvalidCategoryNameException.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature

#97 refactor: Bookmark → UserGroup 으로 테이블명 변경 (#96)
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/usergroup/UserGroup.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java
  src/main/java/com/beside/archivist/repository/usergroup/UserGroupRepository.java
  src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
Labels: refactor

#99 feat: API 요청 시 필수 값에 대한 검증 및 예외 처리 (#89)
  src/main/java/com/beside/archivist/dto/users/UserDto.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
Labels: feature

#101 refactor: 회원이 생성한 그룹 조회 API 변경 (#100)
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/repository/usergroup/UserGroupRepository.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
Labels: refactor

#105 feat: 카카오 인가 코드 만료에 대한 예외 처리 추가 (#103)
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
Labels: feature

#108 fix: API 접근 제어 설정 (#104)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
Labels: fix

#107 feat: 링크 및 그룹 데이터 없을 때 예외 처리 (#102)
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/group/GroupNotFoundException.java
  src/main/java/com/beside/archivist/exception/link/LinkNotFoundException.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature

#110 refactor : API 응답 시 HttpStatus 재정의 (#92)
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
Labels: refactor

#112 chore: Hibernate DDL 자동 설정 update로 변경 (#111)
  src/main/resources/application-prod.properties
Labels: chore

#115 feat: 그룹 썸네일 예외 처리 (#78)
  src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
  src/main/java/com/beside/archivist/entity/group/GroupImg.java
  src/main/java/com/beside/archivist/entity/link/LinkImg.java
  src/main/java/com/beside/archivist/repository/group/GroupRepository.java
  src/main/java/com/beside/archivist/repository/group/LinkGroupRepository.java
  src/main/java/com/beside/archivist/service/group/GroupImgService.java
  src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/group/LinkGroupService.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
Labels: feature, refactor

#120 feat: 요청 헤더에 인증 토큰이 없는 경우 예외 처리 (#109)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/users/MissingAuthenticationException.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
Labels: feature

#119 feat: 그룹 북마크 기능 추가 및 개선 (#116)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/repository/usergroup/UserGroupRepository.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
Labels: feature

#121 fix : Link 와 LinkGroup 간 양방향 설정 (#114)
  src/main/java/com/beside/archivist/entity/link/Link.java
Labels: fix

#122 feature : Delete Soft (#91)
  src/main/java/com/beside/archivist/entity/BaseEntity.java
  src/main/java/com/beside/archivist/entity/BaseTimeEntity.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/group/LinkGroup.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/entity/usergroup/UserGroup.java
Labels: feature

#128 feat: 그룹 북마크 관련 예외 처리 추가(#125)
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/group/GroupAlreadyExistsException.java
  src/main/java/com/beside/archivist/exception/link/GroupInBookmarkNotFoundException.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
Labels: feature

#129 *ImgService 에 정의된 update* 인터페이스명 재정의
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/service/group/GroupImgService.java
  src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkImgService.java
  src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserImgService.java
  src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: refactor

#132 refactor: Entity 내 모든 boolean 필드 타입 변경 (#126)
  src/main/java/com/beside/archivist/dto/group/GroupDto.java
  src/main/java/com/beside/archivist/entity/BaseEntity.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/entity/usergroup/UserGroup.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
Labels: refactor

#135 refactor: 토큰 관련 예외 처리 재정의 (#134)
  src/main/java/com/beside/archivist/config/AuthenticationEntryPointImpl.java
  src/main/java/com/beside/archivist/config/filters/JwtExceptionFilter.java
  src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/users/InvalidTokenException.java
  src/main/java/com/beside/archivist/exception/users/TokenExpiredException.java
Labels: refactor

#137 feature : User email 마스킹 처리 및 Soft Delete 적용 (#133)
  src/main/java/com/beside/archivist/entity/BaseEntity.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: feature

#136 refactor : 그룹 내 링크 추가/수정 기능을 링크 API 에 추가 (#123)
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/dto/link/LinkInfoDto.java
  src/main/java/com/beside/archivist/repository/group/LinkGroupRepository.java
  src/main/java/com/beside/archivist/service/group/LinkGroupService.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
Labels: refactor

#142 chore: 링크/그룹 디폴트 이미지 업로드 (#140)
  src/main/resources/static/default-image/linkDefaultImg.png
Labels: chore
