Repository team-archivist/archivist-backend, pull requests merged in 2024-07, with the labels that each got.

#236 feature: 프론트 테스트 도메인 cors 설정 (#235)
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/WebMvcConfig.java
Labels: feature

#237 fix: 마이프로필 유저 저장 이후 redis 캐시 갱신
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: fix

#238 sync to main
  development/run_local_db.sh
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/WebMvcConfig.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: devops

#239 FE 오피셜 도메인 CORS 화이트리스트 추가
  src/main/java/com/beside/archivist/config/SecurityConfig.java
Labels: chore
