Repository team-archivist/archivist-backend, pull requests merged in 2024-05, with the labels that each got.

#214 isGroupPublic 저장 조건 로직 변경 (#212)
  src/main/java/com/beside/archivist/entity/group/Group.java
Labels: fix

#213 application.yml 내 redis property deprecated 오류 수정 (#211)
  src/main/java/com/beside/archivist/config/RedisConfig.java
  src/main/resources/application.yml
Labels: fix

#217 핫픽스 반영
  src/main/java/com/beside/archivist/config/RedisConfig.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/resources/application.yml
  src/test/java/com/beside/archivist/controller/link/LinkControllerTest.java
  src/test/java/com/beside/archivist/service/group/LinkGroupServiceTest.java
  src/test/java/com/beside/archivist/service/link/LinkServiceTest.java
Labels: devops

#215 LinkDto 와 LinkInfoDto 중복되어 구분 및 정리 (#199)
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/dto/link/LinkDto.java
  src/main/java/com/beside/archivist/dto/link/LinkInfoDto.java
  src/main/java/com/beside/archivist/mapper/LinkMapper.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/test/java/com/beside/archivist/service/group/LinkGroupServiceTest.java
Labels: refactor

#220 fix: Redis password 적용 및 테스트, imgUrl,userId 컬럼 추가 (#218)
  src/main/java/com/beside/archivist/config/RedisConfig.java
  src/main/java/com/beside/archivist/entity/redis/Users.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: fix

#221 LinkGroup - Link,Group 양방향 저장 로직 추가 (#219)
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/repository/group/GroupRepository.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
Labels: fix

#222 Swagger API Description 추가 (#216)
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
Labels: chore

#224 핫픽스 반영
  src/main/java/com/beside/archivist/config/RedisConfig.java
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/link/LinkDto.java
  src/main/java/com/beside/archivist/dto/link/LinkInfoDto.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/entity/redis/Users.java
  src/main/java/com/beside/archivist/mapper/LinkMapper.java
  src/main/java/com/beside/archivist/repository/group/GroupRepository.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
  src/test/java/com/beside/archivist/service/group/LinkGroupServiceTest.java
Labels: devops

#225 홈 피드 API 생성 (#203)
  src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/home/HomeController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/home/HomeFeedDto.java
  src/main/java/com/beside/archivist/dto/home/HomeFeedInfoDto.java
  src/main/java/com/beside/archivist/entity/home/HomeFeed.java
  src/main/java/com/beside/archivist/mapper/GroupMapper.java
  src/main/java/com/beside/archivist/mapper/LinkMapper.java
  src/main/java/com/beside/archivist/repository/home/HomeFeedRepository.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/home/HomeFeedService.java
  src/main/java/com/beside/archivist/service/home/HomeFeedServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
Labels: feature, refactor

#228 groupId 포함하여 Link Service Layer Test Code 재작성 (#163)
  src/test/java/com/beside/archivist/service/link/LinkServiceTest.java
Labels: test

#231 회원 가입 시 기본 그룹 자동 생성 (#230)
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/group/GroupInfoDto.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/service/group/GroupService.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
  src/test/java/com/beside/archivist/service/users/UserServiceTest.java
Labels: feature
