Repository team-archivist/archivist-backend, pull requests merged in 2024-04, with the labels that each got.

#191 Release/v1.1.0
  README.md
  build.gradle
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
  src/main/java/com/beside/archivist/controller/group/GroupController.java
  src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/dto/group/GroupDto.java
  src/main/java/com/beside/archivist/dto/users/UserDto.java
  src/main/java/com/beside/archivist/entity/BaseEntity.java
  src/main/java/com/beside/archivist/entity/group/Group.java
  src/main/java/com/beside/archivist/entity/group/GroupImg.java
  src/main/java/com/beside/archivist/entity/link/Link.java
  src/main/java/com/beside/archivist/entity/link/LinkImg.java
  src/main/java/com/beside/archivist/entity/users/User.java
  src/main/java/com/beside/archivist/entity/users/UserImg.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/exception/group/GroupInBookmarkNotFoundException.java
  src/main/java/com/beside/archivist/exception/images/ImageNotFoundException.java
  src/main/java/com/beside/archivist/exception/link/LinkInGroupNotFoundException.java
  src/main/java/com/beside/archivist/service/group/GroupImgService.java
  src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java
  src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
  src/main/java/com/beside/archivist/service/group/LinkGroupService.java
  src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkImgService.java
  src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
  src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserImgService.java
  src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
  src/main/resources/application-local.properties
  src/main/resources/application-oauth.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/beside/archivist/controller/group/GroupControllerTest.java
  src/test/java/com/beside/archivist/controller/users/UserControllerTest.java
  src/test/java/com/beside/archivist/entity/BaseEntityTest.java
  src/test/java/com/beside/archivist/service/group/GroupServiceTest.java
  src/test/java/com/beside/archivist/service/users/UserImgServiceImplTest.java
  src/test/java/com/beside/archivist/service/users/UserServiceTest.java
Labels: devops

#172 레디스 user조회에 적용(#93)
  build.gradle
  src/main/java/com/beside/archivist/config/RedisConfig.java
  src/main/java/com/beside/archivist/entity/redis/Users.java
  src/main/java/com/beside/archivist/repository/redis/users/UserRedisRepository.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
  src/main/resources/application.yml
Labels: feature

#198 필수 값 누락 시 클라이언트에 누락된 필드명 반환하도록 메시지 수정 (#196)
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
Labels: refactor

#201 링크 이미지 URL Null 값 저장 이슈 (#195)
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
Labels: fix

#197 링크 저장 시 groudId 필수값으로 변경 (#194)
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
Labels: fix

#205 토큰 이슈와 회원 정보가 없는 경우 예외 분리 (#204)
  src/main/java/com/beside/archivist/config/AuthenticationEntryPointImpl.java
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/filters/JwtExceptionFilter.java
  src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
Labels: fix

#209 운영에 Hotfix 반영
  build.gradle
  src/main/java/com/beside/archivist/config/AuthenticationEntryPointImpl.java
  src/main/java/com/beside/archivist/config/RedisConfig.java
  src/main/java/com/beside/archivist/config/SecurityConfig.java
  src/main/java/com/beside/archivist/config/filters/JwtExceptionFilter.java
  src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/controller/users/UserController.java
  src/main/java/com/beside/archivist/entity/redis/Users.java
  src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
  src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
  src/main/java/com/beside/archivist/repository/redis/users/UserRedisRepository.java
  src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
  src/main/java/com/beside/archivist/service/link/LinkService.java
  src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
  src/main/java/com/beside/archivist/service/users/UserService.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
  src/main/resources/application.yml
Labels: fix

#210 HotFix 반영 (#200)
  src/main/java/com/beside/archivist/controller/link/LinkController.java
  src/main/java/com/beside/archivist/dto/link/LinkInfoDto.java
  src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Labels: fix

#207 Link관련 테스트 코드 작성 (#163)
  src/test/java/com/beside/archivist/controller/link/LinkControllerTest.java
  src/test/java/com/beside/archivist/service/link/LinkServiceTest.java
Labels: test

#208 그룹 이미지 업데이트 관련 Test Code 작성 (#173)
  src/test/java/com/beside/archivist/service/group/LinkGroupServiceTest.java
Labels: test
